Movies
VladimirUman/cinema-server pull request #11
Opened 2022-01-21 14:50 UTC by VladimirUman

2022-01-21 14:58 UTC, MaxLogvyniukFive requested changes

2022-01-21 14:58 UTC, MaxLogvyniukFive commented on src/controllers/movies.js
> +            await MovieService.create(movie);
Does this method not return anithing?

2022-01-21 14:58 UTC, MaxLogvyniukFive commented on src/controllers/movies.js
> +                success: true,
Move object in variable

2022-01-21 14:58 UTC, MaxLogvyniukFive commented on src/controllers/movies.js
> +            await MovieService.update(movie);
This method also not return anything?

2022-01-21 14:58 UTC, MaxLogvyniukFive commented on src/controllers/movies.js
> +                success: true,
Variable for object

2022-01-21 16:01 UTC, VladimirUman commented on src/controllers/movies.js
> +            await MovieService.create(movie);
fixed

2022-01-21 16:01 UTC, VladimirUman commented on src/controllers/movies.js
> +                success: true,
fixed

2022-01-21 16:02 UTC, VladimirUman commented on src/controllers/movies.js
> +            await MovieService.update(movie);
fixed

2022-01-21 16:02 UTC, VladimirUman commented on src/controllers/movies.js
> +                success: true,
fixed

2022-01-24 07:31 UTC, MaxLogvyniukFive approved these changes

2022-01-24 09:16 UTC, merged