added refresh tokens
VladimirUman/cinema-server pull request #22
Opened 2022-01-27 14:11 UTC by VladimirUman

2022-01-27 14:45 UTC, MaxLogvyniukFive requested changes

2022-01-27 14:45 UTC, MaxLogvyniukFive commented on src/controllers/auth.js
> -        if (!refreshToken) {
Why did you remove the check?

2022-01-27 14:45 UTC, MaxLogvyniukFive commented on src/controllers/auth.js
> +        const refreshToken = req.body.refreshToken;
Need to check if value exist

2022-01-27 15:02 UTC, VladimirUman commented on src/controllers/auth.js
> +        const refreshToken = req.body.refreshToken;
in validation file

2022-01-28 10:38 UTC, MaxLogvyniukFive approved these changes

2022-01-28 10:48 UTC, merged