Users
VladimirUman/cinema-server pull request #9
Opened 2022-01-20 14:58 UTC by RadetskiyBogdan

2022-01-20 17:40 UTC, MaxLogvyniukFive requested changes

2022-01-20 17:40 UTC, MaxLogvyniukFive commented on src/controllers/users.js
> +            await User.findOneAndDelete({ _id: req.params.id }, (err, user) => {
Move it to service

2022-01-20 17:40 UTC, MaxLogvyniukFive commented on src/controllers/users.js
> +            await User.findOne({ _id: req.params.id }, (err, user) => {
Move it to service

2022-01-20 17:40 UTC, MaxLogvyniukFive commented on src/controllers/users.js
> +            await User.find({}, (err, users) => {
Same

2022-01-24 07:31 UTC, MaxLogvyniukFive requested changes

2022-01-24 07:31 UTC, MaxLogvyniukFive commented on src/controllers/auth.js
> +        let { name, email, lastName, password } = req.body;
Use const

2022-01-24 07:31 UTC, MaxLogvyniukFive commented on src/controllers/test.txt
> +const Movie = require('../models/movie');
?

2022-01-24 09:00 UTC, RadetskiyBogdan commented on src/controllers/test.txt
> +const Movie = require('../models/movie');
accidentally added my notes. already deleted

2022-01-24 12:53 UTC, MaxLogvyniukFive requested changes

2022-01-24 12:53 UTC, MaxLogvyniukFive commented on src/controllers/users.js
> +            const user = await UserService.findById(req.params.id);
Extract "req.params.id" in const and if not received return appropriate server responce

2022-01-24 12:53 UTC, MaxLogvyniukFive commented on src/controllers/users.js
> +            const user = await UserService.findById(req.params.id);
Same here

2022-01-24 13:33 UTC, merged